In [1]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pylab as plt
%matplotlib inline
import pylab as pl
from pandas import *


#read file
dfH= pd.read_csv("usp.csv")
# data clean, only take the useful data from the csv file
data=dfH[['State','Date Local','NO2 Mean', 'NO2 1st Max Value','NO2 AQI','O3 Mean', 'O3 1st Max Value','O3 AQI','SO2 Mean', 'SO2 1st Max Value','SO2 AQI','CO Mean', 'CO 1st Max Value','CO AQI']]
data

,State,Date Local,NO2 Mean,NO2 1st Max Value,NO2 AQI,O3 Mean,O3 1st Max Value,O3 AQI,SO2 Mean,SO2 1st Max Value,SO2 AQI,CO Mean,CO 1st Max Value,CO AQI
0,Arizona,2000-01-01,19.041667,49.0,46,0.022500,0.040,34,3.000000,9.0,13.0,1.145833,4.200,NaN
1,Arizona,2000-01-01,19.041667,49.0,46,0.022500,0.040,34,3.000000,9.0,13.0,0.878947,2.200,25.0
2,Arizona,2000-01-01,19.041667,49.0,46,0.022500,0.040,34,2.975000,6.6,NaN,1.145833,4.200,NaN
3,Arizona,2000-01-01,19.041667,49.0,46,0.022500,0.040,34,2.975000,6.6,NaN,0.878947,2.200,25.0
4,Arizona,2000-01-02,22.958333,36.0,34,0.013375,0.032,27,1.958333,3.0,4.0,0.850000,1.600,NaN
5,Arizona,2000-01-02,22.958333,36.0,34,0.013375,0.032,27,1.958333,3.0,4.0,1.066667,2.300,26.0
6,Arizona,2000-01-02,22.958333,36.0,34,0.013375,0.032,27,1.937500,2.6,NaN,0.850000,1.600,NaN
7,Arizona,2000-01-02,22.958333,36.0,34,0.013375,0.032,27,1.937500,2.6,NaN,1.066667,2.300,26.0
8,Arizona,2000-01-03,38.125000,51.0,48,0.007958,0.016,14,5.250000,11.0,16.0,1.929167,4.400,NaN
9,Arizona,2000-01-03,38.125000,51.0,48,0.007958,0.016,14,5.250000,11.0,16.0,1.762500,2.500,28.0
10,Arizona,2000-01-03,38.125000,51.0,48,0.007958,0.016,14,5.200000,8.3,NaN,1.929167,4.400,NaN
11,Arizona,2000-01-03,38.125000,51.0,48,0.007958,0.016,14,5.200000,8.3,NaN,1.762500,2.500,28.0
12,Arizona,2000-01-04,40.260870,74.0,72,0.014167,0.033,28,7.083333,16.0,23.0,1.991667,5.100,NaN
13,Arizona,2000-01-04,40.260870,74.0,72,0.014167,0.033,28,7.083333,16.0,23.0,1.829167,3.000,34.0
14,Arizona,2000-01-04,40.260870,74.0,72,0.014167,0.033,28,7.050000,12.6,NaN,1.991667,5.100,NaN
15,Arizona,2000-01-04,40.260870,74.0,72,0.014167,0.033,28,7.050000,12.6,NaN,1.829167,3.000,34.0
16,Arizona,2000-01-05,48.450000,61.0,58,0.006667,0.012,10,8.708333,15.0,21.0,2.620833,5.600,NaN
17,Arizona,2000-01-05,48.450000,61.0,58,0.006667,0.012,10,8.708333,15.0,21.0,2.700000,3.700,42.0
18,Arizona,2000-01-05,48.450000,61.0,58,0.006667,0.012,10,8.700000,14.0,NaN,2.620833,5.600,NaN
19,Arizona,2000-01-05,48.450000,61.0,58,0.006667,0.012,10,8.700000,14.0,NaN,2.700000,3.700,42.0
20,Arizona,2000-01-06,39.950000,73.0,71,0.011750,0.025,21,6.761905,17.0,24.0,1.973913,6.300,NaN
21,Arizona,2000-01-06,39.950000,73.0,71,0.011750,0.025,21,6.761905,17.0,24.0,2.308333,3.600,41.0
22,Arizona,2000-01-06,39.950000,73.0,71,0.011750,0.025,21,7.066667,14.6,NaN,1.973913,6.300,NaN
23,Arizona,2000-01-06,39.950000,73.0,71,0.011750,0.025,21,7.066667,14.6,NaN,2.308333,3.600,41.0
24,Arizona,2000-01-07,29.625000,43.0,41,0.011625,0.024,20,8.666667,21.0,30.0,2.362500,6.400,NaN
25,Arizona,2000-01-07,29.625000,43.0,41,0.011625,0.024,20,8.666667,21.0,30.0,1.829167,3.500,40.0
26,Arizona,2000-01-07,29.625000,43.0,41,0.011625,0.024,20,8.637500,17.3,NaN,2.362500,6.400,NaN
27,Arizona,2000-01-07,29.625000,43.0,41,0.011625,0.024,20,8.637500,17.3,NaN,1.829167,3.500,40.0
28,Arizona,2000-01-08,29.666667,41.0,39,0.009750,0.020,17,8.250000,18.0,26.0,2.541667,6.600,NaN
29,Arizona,2000-01-08,29.666667,41.0,39,0.009750,0.020,17,8.250000,18.0,26.0,2.787500,5.100,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746631,Wyoming,2016-03-24,2.212500,8.9,8,0.044792,0.049,45,-0.075000,0.0,NaN,0.117792,0.154,NaN
1746632,Wyoming,2016-03-24,2.212500,8.9,8,0.044792,0.049,45,-0.075000,0.0,NaN,0.100000,0.100,1.0
1746633,Wyoming,2016-03-25,1.626087,10.9,9,0.041708,0.049,45,-0.031818,0.1,0.0,0.075909,0.154,NaN
1746634,Wyoming,2016-03-25,1.626087,10.9,9,0.041708,0.049,45,-0.031818,0.1,0.0,0.100000,0.100,1.0
1746635,Wyoming,2016-03-25,1.626087,10.9,9,0.041708,0.049,45,-0.028571,0.0,NaN,0.075909,0.154,NaN
1746636,Wyoming,2016-03-25,1.626087,10.9,9,0.041708,0.049,45,-0.028571,0.0,NaN,0.100000,0.100,1.0
1746637,Wyoming,2016-03-26,3.758333,27.6,25,0.033292,0.041,38,-0.050000,0.3,0.0,0.103417,0.212,NaN
1746638,Wyoming,2016-03-26,3.758333,27.6,25,0.033292,0.041,38,-0.050000,0.3,0.0,0.100000,0.100,1.0
1746639,Wyoming,2016-03-26,3.758333,27.6,25,0.033292,0.041,38,-0.037500,0.1,NaN,0.103417,0.212,NaN
1746640,Wyoming,2016-03-26,3.758333,27.6,25,0.033292,0.041,38,-0.037500,0.1,NaN,0.100000,0.100,1.0
1746641,Wyoming,2016-03-27,4.277273,23.5,22,0.041958,0.050,46,-0.095238,0.0,0.0,0.093000,0.119,NaN
1746642,Wyoming,2016-03-27,4.277273,23.5,22,0.041958,0.050,46,-0.095238,0.0,0.0,0.100000,0.100,1.0
1746643,Wyoming,2016-03-27,4.277273,23.5,22,0.041958,0.050,46,-0.066667,0.0,NaN,0.093000,0.119,NaN
1746644,Wyoming,2016-03-27,4.277273,23.5,22,0.041958,0.050,46,-0.066667,0.0,NaN,0.100000,0.100,1.0
1746645,Wyoming,2016-03-28,8.317391,22.6,21,0.041292,0.052,48,0.117391,0.5,0.0,0.069304,0.139,NaN
1746646,Wyoming,2016-03-28,8.317391,22.6,21,0.041292,0.052,48,0.117391,0.5,0.0,0.100000,0.100,1.0
1746647,Wyoming,2016-03-28,8.317391,22.6,21,0.041292,0.052,48,0.100000,0.4,NaN,0.069304,0.139,NaN
1746648,Wyoming,2016-03-28,8.317391,22.6,21,0.041292,0.052,48,0.100000,0.4,NaN,0.100000,0.100,1.0
1746649,Wyoming,2016-03-29,2.564706,3.6,3,0.028000,0.040,37,0.143750,0.7,0.0,0.045625,0.071,NaN
1746650,Wyoming,2016-03-29,2.564706,3.6,3,0.028000,0.040,37,0.143750,0.7,0.0,0.006667,0.100,1.0
1746651,Wyoming,2016-03-29,2.564706,3.6,3,0.028000,0.040,37,0.120000,0.4,NaN,0.045625,0.071,NaN
1746652,Wyoming,2016-03-29,2.564706,3.6,3,0.028000,0.040,37,0.120000,0.4,NaN,0.006667,0.100,1.0
1746653,Wyoming,2016-03-30,1.083333,1.6,1,0.043917,0.048,44,0.016667,0.1,0.0,0.101042,0.134,NaN
1746654,Wyoming,2016-03-30,1.083333,1.6,1,0.043917,0.048,44,0.016667,0.1,0.0,0.091667,0.100,1.0
1746655,Wyoming,2016-03-30,1.083333,1.6,1,0.043917,0.048,44,0.000000,0.0,NaN,0.101042,0.134,NaN
1746656,Wyoming,2016-03-30,1.083333,1.6,1,0.043917,0.048,44,0.000000,0.0,NaN,0.091667,0.100,1.0
1746657,Wyoming,2016-03-31,0.939130,1.3,1,0.045263,0.047,44,-0.022727,0.0,0.0,0.067714,0.127,NaN
1746658,Wyoming,2016-03-31,0.939130,1.3,1,0.045263,0.047,44,-0.022727,0.0,0.0,0.100000,0.100,1.0
1746659,Wyoming,2016-03-31,0.939130,1.3,1,0.045263,0.047,44,0.000000,0.0,NaN,0.067714,0.127,NaN
1746660,Wyoming,2016-03-31,0.939130,1.3,1,0.045263,0.047,44,0.000000,0.0,NaN,0.100000,0.100,1.0

In [4]:
data1=data[(data.State=='Colorado')]
data1['Date Local'] = data1['Date Local'].str.split('-').str[0].astype(int)
data1 = data1[["Date Local", "NO2 AQI", "O3 AQI", "SO2 AQI","CO AQI"]].groupby("Date Local").mean()
data1
#data1.to_csv("Colorado pollution.csv")

/Users/SUPERCZX/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

              NO2 AQI     O3 AQI    SO2 AQI     CO AQI
Date Local
2000        32.753425  27.553425  21.509589  11.558904
2001        48.031153  27.118380  23.987539  11.925234
2002        37.909761  33.101289  22.454880   9.525735
2003        40.935750  31.573311  19.098847  10.232787
2004        39.886297  27.084548  15.641399  10.612245
2005        42.677073  30.237073  13.559454  10.208780
2006        42.233645  29.401869  13.172897   9.855140
2007        41.503587  31.203730  12.527977   9.407461
2008        38.670773  37.995893  11.157319   7.501370
2009        30.618750  38.800000  10.121875   6.515625
2010        31.224057  32.603774   7.738208   6.679245
2011        36.067504  42.070644   8.883830   5.767296
2012        36.447214  35.546188   9.213919   6.184615
2013        25.502857  39.153333   7.086667   5.089524
2014        30.119482  38.460365   4.291917   5.431082
2015        35.530681  38.639501   4.927613   6.544498
2016        42.159851  31.286245   3.947955   7.843866

In [14]:
data6=data[['State','NO2 AQI','O3 AQI','SO2 AQI','CO AQI']]
data6
state1=data6[(data6.State=='California')]
state2=data6[(data6.State=='Colorado')]
state3=data6[(data6.State=='Florida')]
state4=data6[(data6.State=='New York')]
total=state1.append(state2).append(state3).append(state4)
total=total.groupby("State").mean()
final=total.dropna()
final.to_csv("four state aqi.csv")
final

              NO2 AQI     O3 AQI    SO2 AQI    CO AQI
State
California  24.110238  35.722673   3.598278  7.405669
Colorado    35.958878  34.673582  10.605523  7.724205
Florida     16.384443  36.000077   2.876997  5.921593
New York    30.580334  31.785535  14.061590  5.657804